## Tensor
- deeplearning framework는 기본적으로 Tensor를 다루는 도구
- Tensor: 구조적으로 쌓여있는 숫자의 집합 ex)벡터, 행렬 등
- Tensor를 다룰 때 가장 중요한 것 : shape

## Tensor 생성
- sork todtjdgksms rjtdms <code>tf.Tensor</code> 데이터
- 항상 체크해야 하는 것: shape, dtype(타입이 같아야 연산 가능

In [5]:
import tensorflow as tf
import numpy as np

# Constant(상수)
- 숫자는 상수, 변수 두가지로 나뉜다.

- <code>tf.constant()</code> : 기존 list, tuple, array 를 Tensor로 만들어준다.
- shape, dtype 값을 집중해서 보자!

In [2]:
li_ten = tf.constant([1, 2, 3])
li_ten

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [3]:
li_ten_f = tf.constant([1., 2., 3.])
li_ten_f

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [4]:
tu_ten = tf.constant(((1, 2, 3), (1, 2, 3)), name="sample")
tu_ten

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [1, 2, 3]])>

In [6]:
arr = np.array([1., 2., 3.])
arr_ten = tf.constant(arr)
arr_ten

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([1., 2., 3.])>

## Tensor에서 Numpy array 추출

In [7]:
print(arr_ten.numpy())
print(type(arr_ten.numpy()))

[1. 2. 3.]
<class 'numpy.ndarray'>


In [8]:
print(li_ten.numpy())
print(type(li_ten.numpy()))

[1 2 3]
<class 'numpy.ndarray'>


```
not_a_matrix = [[1, 2, 3], [4, 5], [6, 7, 8]]
- 구조적이지 않은 형태는 tf.constant() 불가능. list 형태만 가능
```

## shape, dtype 항상 체크!

In [9]:
print(li_ten.shape)
print(tu_ten.shape)

(3,)
(2, 3)


In [ ]:
# shape 이 다른 것끼리 연산
tf.matmul(li_ten,tu_ten)  # 내적

In [ ]:
# shape 이 다른 것끼리 연산
tf.matmul(tu_ten, li_ten)  # 내적

- 내적은 (2, 3), (3, 1)이면 가능해야 하는데, tf.matmul() 에서는 rank값(행 수)이 같지 않아서 불가능하다.

In [15]:
# rank 확인
print(li_ten.ndim)
print(tu_ten.ndim)

1
2


In [10]:
print(li_ten.dtype)
print(arr_ten.dtype)

<dtype: 'int32'>
<dtype: 'float64'>


In [ ]:
# dtype이 다른 것끼리 연산
arr_ten * li_ten

## 데이터 타입 컨트롤하는 방법

### 1. 미리 지정

In [16]:
tensor = tf.constant([1, 2, 3], dtype=tf.float32)
tensor

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

### 2. <code>tf.cast</code> 사용

In [17]:
tf.cast(tensor, dtype=tf.int16)

<tf.Tensor: shape=(3,), dtype=int16, numpy=array([1, 2, 3], dtype=int16)>

## 특정 값의 Tensor 생성
- <code>tf.ones</code>
- <code>tf.zeros</code>
- <code>tf.range</code>

In [18]:
tf.ones(1)

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>

In [19]:
tf.zeros((2, 5), dtype='int32')

<tf.Tensor: shape=(2, 5), dtype=int32, numpy=
array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])>

In [20]:
tf.range(10)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [22]:
tf.range(1, 11, 2)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 3, 5, 7, 9])>

## Random Value(난수)
- 무작위 값을 생성할 때 필요
- noisw재현, test 실행 시 사용
- 데이터 타입은은 상수형태로 반환

##### <code>tf.random</code> 에서 구현 가능
- <code>tf.random.normal</code> : 정규분포
- <code>tf.random.uniform</code> : Uniform 분포

In [24]:
shape = (3, 3) # shape은 튜플 형태로 입력해야 한다

In [25]:
tf.random.normal(shape) # 평균과 분산값을 임의로 지정 가능

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.43311214,  1.413136  ,  0.387085  ],
       [-0.85273725,  0.88912535,  0.7022076 ],
       [-0.4574507 ,  0.69451326, -0.7225395 ]], dtype=float32)>

In [26]:
tf.random.uniform(shape)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.9383218 , 0.8092319 , 0.61070526],
       [0.79136205, 0.6807728 , 0.8633183 ],
       [0.1760205 , 0.27090085, 0.9975245 ]], dtype=float32)>

### Random Seed 관리 하기
- <code>tf.random.set_seed({seed_number})</code>

In [27]:
seed = 7777

In [29]:
tf.random.set_seed(seed)
a = tf.random.uniform([1])
b = tf.random.uniform([1])
print(a, b, sep="\n")

tf.Tensor([0.959749], shape=(1,), dtype=float32)
tf.Tensor([0.8677443], shape=(1,), dtype=float32)


In [30]:
a = tf.random.uniform([1])
b = tf.random.uniform([1])
print(a, b, sep="\n")

tf.Tensor([0.22878075], shape=(1,), dtype=float32)
tf.Tensor([0.87772965], shape=(1,), dtype=float32)


In [31]:
tf.random.set_seed(seed)
a = tf.random.uniform([1])
b = tf.random.uniform([1])
print(a, b, sep="\n")

tf.Tensor([0.959749], shape=(1,), dtype=float32)
tf.Tensor([0.8677443], shape=(1,), dtype=float32)
