In [1]:
import tensorflow as tf
import numpy as np

# Tensor연산
아래의 기본 연산은 특수 매서드를 이용하여 연산자 오버로딩이 되어 있으므로, 그냥 연산자 기호를 사용하는 게 가능
- `tf.add`:덧셈
- `tf.subtract`:뺄셈
- `tf.multiply`:곱셈
- `tf.divide`:나눗셈
- `tf.pow`:제곱
- `tf.negative`:음수부호

In [3]:
a = tf.range(6, dtype="int32")
b = 2*tf.ones(6, dtype='int32')

tf.add(a, b)

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([2, 3, 4, 5, 6, 7])>

In [4]:
a+b

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([2, 3, 4, 5, 6, 7])>

## 여러가지 연산
- `tf.abs`:절대값
- `tf.sign`:부호
- `tf.round`:반올림
- `tf.ceil`:올림
- `tf.floor`:내림
- `tf.square`:제곱
- `tf.sqrt`:제곱근
- `tf.maximum`:두 텐서의 각 원소에서 최대값만 반환
- `tf.minimum`: 두 텐서의 각 원소에서 최솟값만 반환
- `tf.cumsum`:누적합
- `tf.cumprod`:누적곱

In [5]:
tf.maximum(a, b)

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([2, 2, 2, 3, 4, 5])>

In [6]:
tf.sqrt(tf.cast(a, tf.float32))

<tf.Tensor: shape=(6,), dtype=float32, numpy=
array([0.       , 1.       , 1.4142135, 1.7320508, 2.       , 2.236068 ],
      dtype=float32)>

## Axis 이해하기

In [7]:
rank_2 = tf.random.normal((3, 3))
rank_2

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-1.581969  ,  0.0331114 , -2.3940187 ],
       [-1.1971556 , -0.10683604, -0.22194177],
       [-2.4325974 ,  0.46138558, -1.2493757 ]], dtype=float32)>

In [8]:
rank_2[1]

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([-1.1971556 , -0.10683604, -0.22194177], dtype=float32)>

In [9]:
rank_2[1, 2]

<tf.Tensor: shape=(), dtype=float32, numpy=-0.22194177>

In [10]:
rank_3 = tf.random.normal((3, 3, 3))
rank_3

<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
array([[[ 1.4578198 , -0.49190137, -0.41990036],
        [-0.09744671,  0.09744209,  1.5048529 ],
        [ 1.2968284 , -0.76687443,  0.69980395]],

       [[ 1.155103  , -0.92086995,  1.2764422 ],
        [-0.8823539 , -0.7950498 , -1.8147137 ],
        [-0.08087288, -3.0330548 , -1.9147419 ]],

       [[ 0.27394328, -0.03218214,  1.1135783 ],
        [-0.937448  , -0.610846  ,  1.6937248 ],
        [-0.63585883, -0.75830764,  1.283583  ]]], dtype=float32)>

 ## 차원축소연산
- `tf.reduce_mean`:설정한 축의 평균을 구한다
- `tf.reduce_max`:설정한 축의 최대값
- `tf.reduce_min`: 설정한 축의 최솟값
- `tf.reduce_prod`:설정한 축의 요소를 모두 곱한 값
- `tf.reduce_sum`:설정한 축의 요소를 모두 더한 값

In [11]:
a

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5])>

In [12]:
tf.reduce_sum(a, axis=0)

<tf.Tensor: shape=(), dtype=int32, numpy=15>

In [13]:
tf.reduce_sum(a, axis=0, keepdims=True)

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([15])>

In [16]:
b = tf.random.normal((2, 4, 3))
b

<tf.Tensor: shape=(2, 4, 3), dtype=float32, numpy=
array([[[ 0.01747768, -0.46500602, -1.955529  ],
        [ 0.39811966, -1.9748548 , -0.8646807 ],
        [ 0.28892848,  0.5696079 ,  1.0596219 ],
        [ 0.19579932, -0.8834644 , -0.70702696]],

       [[ 1.072388  ,  0.09778222, -0.0999762 ],
        [ 0.46455625, -0.00732202,  0.034938  ],
        [-0.01832083, -0.9854164 , -1.0013884 ],
        [-0.30025977,  1.3151168 ,  0.02515507]]], dtype=float32)>

In [17]:
tf.reduce_mean(b, 0)

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[ 0.54493284, -0.1836119 , -1.0277526 ],
       [ 0.43133795, -0.99108845, -0.41487136],
       [ 0.13530383, -0.20790425,  0.02911675],
       [-0.05223022,  0.21582618, -0.34093595]], dtype=float32)>

In [18]:
tf.reduce_mean(b, 1)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 0.2250813 , -0.6884293 , -0.61690366],
       [ 0.30459094,  0.10504013, -0.2603179 ]], dtype=float32)>

In [19]:
tf.reduce_mean(b, 2)

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[-0.80101913, -0.8138053 ,  0.6393861 , -0.46489736],
       [ 0.35673138,  0.16405742, -0.6683752 ,  0.34667072]],
      dtype=float32)>

## 행렬과 관련된 연산
- `tf.matmul`:내적
- `tf.linalg.inv`:역행렬

In [21]:
a = tf.constant([[2, 0], [0, 1]], dtype='float32')
b = tf.constant([[1, 1], [1, 1]], dtype='float32')
tf.matmul(a, b)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 2.],
       [1., 1.]], dtype=float32)>

In [22]:
a = tf.constant([[2, 0], [0, 1]], dtype='float32')
tf.linalg.inv(a)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.5, 0. ],
       [0. , 1. ]], dtype=float32)>

## 크기 및 차원을 바꾸는 명령
- `tf.reshape`:벡터 행렬의 크기변환
- `tf.transpose`:전치연산
- `tf.expand_dims`:지정한 축으로 차원 추가
- `tf.squeeze`:벡터 차원을 축소

In [23]:
a = tf.range(6, dtype=tf.int32)
a

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5])>

In [25]:
a_2d = tf.reshape(a, (2,3)) 
a_2d

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5]])>

- 1차원 벡터를 2x3 크기의 2차원 행렬로 변환

In [26]:
a_2d_t = tf.transpose(a_2d)
a_2d_t

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[0, 3],
       [1, 4],
       [2, 5]])>

- 2x3 행렬을 3x2 행렬로 변환

In [27]:
a_3d = tf.expand_dims(a_2d, 0)
a_3d

<tf.Tensor: shape=(1, 2, 3), dtype=int32, numpy=
array([[[0, 1, 2],
        [3, 4, 5]]])>

- 2x3 행렬을 1x2x3 행렬로 변환

In [31]:
tf.expand_dims(a_2d, 1)

<tf.Tensor: shape=(2, 1, 3), dtype=int32, numpy=
array([[[0, 1, 2]],

       [[3, 4, 5]]])>

- 2x3 행렬을 2x1x3 행렬로 변환

In [29]:
a_4d = tf.expand_dims(a_3d, 3)
a_4d

<tf.Tensor: shape=(1, 2, 3, 1), dtype=int32, numpy=
array([[[[0],
         [1],
         [2]],

        [[3],
         [4],
         [5]]]])>

- 1x2x3 행렬을 1x2x3x1 행렬로 변환

In [30]:
a_1d = tf.squeeze(a_4d)
a_1d

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5]])>

- 1x2x3x1 행렬에서 원소 개수가 1인 차원을 모두 없앤다.
- axis=3 처럼 특정 차원만 지정 가능
- 근데 axis=2 처럼 원소개수가 1이 아닌 차원을 지정하면 오류가 발생한다.

## 텐서를 나누거나 두개 이상의 텐서를 합치는 명령

- `tf.slice`:특정 부분을 추출
- `tf.split`:분할
- `tf.concat`:합치기
- `tf.tile`:복제-붙이기
- `tf.stack`:합성
- `tf.unstack`:분리

In [36]:
a = tf.reshape(tf.range(12), (3, 4))
a

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])>

In [37]:
tf.slice(a, [0, 1], [2, 3]) 

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [5, 6, 7]])>

- [0, 1]위치를 기준으로 [2, 3]만큼 뽑아낸다.

In [38]:
a1, a2 = tf.split(a, num_or_size_splits=2, axis=1)
print(a1)
print(a2)

tf.Tensor(
[[0 1]
 [4 5]
 [8 9]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[ 2  3]
 [ 6  7]
 [10 11]], shape=(3, 2), dtype=int32)


- 가로축(axis=1)을 따라 2개로 분할

In [39]:
tf.concat([a1, a2], 1)

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])>

- axis=1을 기준으로 합침

In [44]:
tf.concat([a1, a2],0)

<tf.Tensor: shape=(6, 2), dtype=int32, numpy=
array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [ 2,  3],
       [ 6,  7],
       [10, 11]])>

- axis=0을 기준으로 합침

In [40]:
tf.tile(a1, [1, 3])

<tf.Tensor: shape=(3, 6), dtype=int32, numpy=
array([[0, 1, 0, 1, 0, 1],
       [4, 5, 4, 5, 4, 5],
       [8, 9, 8, 9, 8, 9]])>

- a1을 [1, 3] 행렬로 배치

In [42]:
tf.tile(a1, [2, 3])

<tf.Tensor: shape=(6, 6), dtype=int32, numpy=
array([[0, 1, 0, 1, 0, 1],
       [4, 5, 4, 5, 4, 5],
       [8, 9, 8, 9, 8, 9],
       [0, 1, 0, 1, 0, 1],
       [4, 5, 4, 5, 4, 5],
       [8, 9, 8, 9, 8, 9]])>

- a1을 [2, 3] 행렬로 배치

In [43]:
a3 = tf.stack([a1, a2])
a3

<tf.Tensor: shape=(2, 3, 2), dtype=int32, numpy=
array([[[ 0,  1],
        [ 4,  5],
        [ 8,  9]],

       [[ 2,  3],
        [ 6,  7],
        [10, 11]]])>

- 3x2 행렬인 a1, a2를 추가적인 차원으로 붙여서 2x3x2 행렬 생성

In [47]:
tf.unstack(a3, axis=0)

[<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[0, 1],
        [4, 5],
        [8, 9]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])>]

- 2x3x2 행렬을 axis=0 을 기준으로 풀어서 3x2 행렬 생성 

In [46]:
tf.unstack(a3, axis=1)

[<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[0, 1],
        [2, 3]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[4, 5],
        [6, 7]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 8,  9],
        [10, 11]])>]

- 2x3x2 행렬을 axis=1 을 기준으로 풀어서 2x2 행렬 생성

In [48]:
tf.unstack(a3, axis=2)

[<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 0,  4,  8],
        [ 2,  6, 10]])>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 1,  5,  9],
        [ 3,  7, 11]])>]

- 2x3x2 행렬을 axis=2 을 기준으로 풀어서 2x3 행렬 생성