# Tensor 생성

In [3]:
import torch
import numpy as np

## 1. 기존 데이터를 Torch의 Tensor로 
- `torch.tensor()`
- `torch.as_tensor()`
- `torch.from_numpy()`

#### list

In [2]:
li = [[1, 2], [3, 4]]

li_tensor = torch.tensor(li)
li_as_tensor = torch.as_tensor(li)

print(li_tensor)
print(li_tensor.shape)
print(li_tensor.dtype)
print("-" * 10)
print(li_as_tensor)
print(li_as_tensor.shape)
print(li_as_tensor.dtype)

tensor([[1, 2],
        [3, 4]])
torch.Size([2, 2])
torch.int64
----------
tensor([[1, 2],
        [3, 4]])
torch.Size([2, 2])
torch.int64


#### array

In [4]:
arr = np.array([[1, 2], [3, 4]])

arr_tensor = torch.tensor(arr)
arr_as_tensor = torch.as_tensor(arr)
arr_from_numpy = torch.from_numpy(arr)

print(arr_tensor)
print(arr_tensor.shape)
print(arr_tensor.dtype)
print("-" * 10)
print(arr_as_tensor)
print(arr_as_tensor.shape)
print(arr_as_tensor.dtype)
print("-" * 10)
print(arr_from_numpy)
print(arr_from_numpy.shape)
print(arr_from_numpy.dtype)

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
torch.Size([2, 2])
torch.int32
----------
tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
torch.Size([2, 2])
torch.int32
----------
tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
torch.Size([2, 2])
torch.int32


#### 속성값 확인

In [5]:
li_tensor.shape

torch.Size([2, 2])

In [6]:
li_tensor.size()

torch.Size([2, 2])

---
## 2. Torch를 numpy 배열로
- `.numpy()`

In [7]:
print(li_tensor.numpy())
print(arr_as_tensor.numpy())
print(arr_from_numpy.numpy())

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


## 3. 특정한 값의 Tensor 생성
- `torch.arange()`
- `torch.ones()`
- `torch.zeros()`
- `torch.ones_like()` : 입력값은 Tensor 형태만 가능
- `torch.zeros_like()` : 입력값은 Tensor 형태만 가능
- `torch.linspace(시작값, 끝값, 구간개수)`
- `torch.logspace(시작값, 끝값, 구간개수)`

In [8]:
torch.arange(10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
print(torch.ones(5))
print(torch.zeros(5))

tensor([1., 1., 1., 1., 1.])
tensor([0., 0., 0., 0., 0.])


In [10]:
torch.ones_like(li_tensor)

tensor([[1, 1],
        [1, 1]])

In [12]:
torch.zeros_like(li_tensor)

tensor([[0, 0],
        [0, 0]])

In [13]:
 torch.zeros_like(arr)

TypeError: zeros_like(): argument 'input' (position 1) must be Tensor, not numpy.ndarray

In [16]:
torch.linspace(0, 10, 5)

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])

In [15]:
torch.logspace(0, 10, 5)

tensor([1.0000e+00, 3.1623e+02, 1.0000e+05, 3.1623e+07, 1.0000e+10])

## 4. 난수 생성
- `torch.rand(출력개수)` : 균등분포
- `torch.randn(출력개수)` : 정규분포
- `torch.randint()` : 균등분포, size만큼 출력(size는 항상 튜플로 입력!)

In [17]:
# seed 조절 꼭 하기!
torch.manual_seed(0)

In [18]:
a = torch.rand(5)
b = torch.randn(5)
c = torch.randint(10, size = (5,))

print(a, b, c, sep="\n")

tensor([0.4963, 0.7682, 0.0885, 0.1320, 0.3074])
tensor([ 0.5507,  0.2704,  0.6472,  0.2490, -0.3354])
tensor([8, 4, 3, 6, 9])


## 5. 데이터 타입
- tf와 동일하게 데이터 타입이 다르면 연산이 불가능하다

#### 생성 시 선언

In [19]:
torch.randint(10, size=(5, ), dtype=torch.float32)

tensor([1., 4., 4., 1., 9.])

#### 생성 후 선언

In [20]:
a = torch.randint(10, size=(5,))
print(a.dtype)

print(a.type(torch.float32))
print(a.dtype)  # .type()는 inplace 되는 명령이 아님!

a = a.type(torch.float64)  # 변한 dtype으로 갱신을 따로 해줘야 한다!
print(a.dtype)

torch.int64
tensor([9., 9., 0., 1., 2.])
torch.int64
torch.float64


## 6. GPU 사용하기
TensorFlow는 자동으로 GPU를 사용하지만, Torch에서는 GPU 사용을 위해서 데이터 타입을 변환해줘야 한다.

In [22]:
torch.cuda.is_available()

False

- GPU 사용이 가능한 경우에는 True 가 출력된다.

### GPU 를 사용하기 위해 Cuda에서 사용하는 데이터타입으로 바꾸어줘야 한다. 
### 방법 세가지! 

 - 만들 때, device 설정해두기
 - tensor_var.cuda()
 - tensor_var.to(device)


#### device 설정하기.

In [ ]:
x = torch.ones(2, 2, device='cuda')

# 여러개 GPU중에 하나의 GPU에 할당하고 싶을 때
# 번호는 nvidia-smi 명령을 Shell에 입력해서 찾을 수 있음 
x = torch.ones(2, 2, device='cuda:0')

# device 객체를 입력하는게 기본
x = torch.ones(2, 2, device=torch.device('cuda'))

#### .cuda()

In [ ]:
a = torch.rand(10)
print(a)

a = a.cuda()
print(a)

#### .to(device)

In [ ]:
a = torch.rand(2)
print(a)

a = a.to("cuda")
print(a)

#### 가장 보편적인 방법

In [24]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

a = torch.rand(2)
print(a)

a = a.to(device)
print(a)

cpu
tensor([0.1759, 0.2698])
tensor([0.1759, 0.2698])
