In [1]:
import torch

# 1. 기본 연산

In [2]:
x = torch.arange(0, 5)
y = torch.arange(1, 6)

#### 더하기

In [3]:
print(x+y)
print(torch.add(x, y))
print(x.add(y))

tensor([1, 3, 5, 7, 9])
tensor([1, 3, 5, 7, 9])
tensor([1, 3, 5, 7, 9])


#### 빼기

In [4]:
print(x-y)
print(torch.sub(x, y))
print(x.sub(y))

tensor([-1, -1, -1, -1, -1])
tensor([-1, -1, -1, -1, -1])
tensor([-1, -1, -1, -1, -1])


#### 곱하기

In [5]:
print(x * y)
print(torch.mul(x, y))
print(x.mul(y))

tensor([ 0,  2,  6, 12, 20])
tensor([ 0,  2,  6, 12, 20])
tensor([ 0,  2,  6, 12, 20])


#### 나누기

In [7]:
print(x / y)
print(torch.div(x, y))
print(x.div(y))

tensor([0.0000, 0.5000, 0.6667, 0.7500, 0.8000])
tensor([0.0000, 0.5000, 0.6667, 0.7500, 0.8000])
tensor([0.0000, 0.5000, 0.6667, 0.7500, 0.8000])


#### 제곱

In [8]:
print(x ** y)
print(torch.pow(x, y))
print(x.pow(y))

tensor([   0,    1,    8,   81, 1024])
tensor([   0,    1,    8,   81, 1024])
tensor([   0,    1,    8,   81, 1024])


#### 부호 전환

In [9]:
print(-x)
print(torch.negative(x))
print(x.negative())

tensor([ 0, -1, -2, -3, -4])
tensor([ 0, -1, -2, -3, -4])
tensor([ 0, -1, -2, -3, -4])


## 그 외 연산
* `torch.abs`: 절대값
* `torch.sign`: 부호
* `torch.round`: 반올림
* `torch.ceil`: 올림
* `torch.floor`: 내림
* `torch.square`: 제곱
* `torch.sqrt`: 제곱근
* `torch.maximum`: 두 텐서의 각 원소에서 최댓값만 반환.
* `torch.minimum`: 두 텐서의 각 원소에서 최솟값만 반환.
* `torch.cumsum`: 누적합
* `torch.cumprod`: 누적곱


---
# 2. 차원 축소 연산

PyTorch는 기본이 reduce 연산 <br>
sum, product, mean 등

In [10]:
x = torch.randint(10, size=(5, 2, 4))
print(x.shape)
print(x)

torch.Size([5, 2, 4])
tensor([[[0, 1, 9, 7],
         [4, 2, 7, 7]],

        [[7, 0, 3, 5],
         [9, 8, 8, 1]],

        [[7, 9, 4, 7],
         [6, 3, 4, 3]],

        [[5, 9, 9, 1],
         [9, 7, 3, 0]],

        [[8, 2, 1, 7],
         [4, 6, 4, 4]]])


In [12]:
print(torch.sum(x)) # x의 모든 원소를 다 더한 값
print(torch.sum(x).shape)

tensor(200)
torch.Size([])


In [13]:
print(torch.sum(x, dim=1))
print(torch.sum(x, dim=1).shape)

tensor([[ 4,  3, 16, 14],
        [16,  8, 11,  6],
        [13, 12,  8, 10],
        [14, 16, 12,  1],
        [12,  8,  5, 11]])
torch.Size([5, 4])


In [14]:
print(torch.sum(x, dim=2))
print(torch.sum(x, dim=2).shape)

tensor([[17, 20],
        [15, 26],
        [27, 16],
        [24, 19],
        [18, 18]])
torch.Size([5, 2])


# 3. 행렬연산
- `torch.matmul(a, b)` = `torch.mm(a, b)` : 내적
- `torch.linalg.inv(a)` : 역행렬
  

In [15]:
a = torch.tensor([[2, 0], [0, 1]], dtype=torch.float32)
b = torch.tensor([[1, 1], [1, 1]], dtype=torch.float32)

In [16]:
torch.matmul(a, b)

tensor([[2., 2.],
        [1., 1.]])

In [18]:
torch.mm(a, b)

tensor([[2., 2.],
        [1., 1.]])

In [17]:
torch.linalg.inv(a)

tensor([[0.5000, 0.0000],
        [0.0000, 1.0000]])

# 4. 크기와 차원을 바꾸는 명령
- `torch.reshape`
- `.view`
- `torch.transpose`

torch.view() 는 불가능

#### view()

In [24]:
a

tensor([[2., 0.],
        [0., 1.]])

In [23]:
print(a.view(4, -1))
print(a.view((4, -1)))

tensor([[2.],
        [0.],
        [0.],
        [1.]])
tensor([[2.],
        [0.],
        [0.],
        [1.]])


In [21]:
print(a.view(4, -1).shape)
print(a.view((4, -1)).shape)

torch.Size([4, 1])
torch.Size([4, 1])


In [25]:
torch.reshape(a, (4, -1))

tensor([[2.],
        [0.],
        [0.],
        [1.]])

#### view 함수가 있어서 exdand_dim 같은 함수가 따로 필요하지 않다
= 차원추가는 view 함수로도 가능

In [27]:
a.view((1, 4, 1)), a.view((1, 4, 1)).shape

(tensor([[[2.],
          [0.],
          [0.],
          [1.]]]),
 torch.Size([1, 4, 1]))

- (1, 4, 1) 형태의 3차원 행렬로 쉽게 변환 성공!

In [28]:
print(torch.squeeze(a.view((1, 4, 1)), dim=2))
print(torch.squeeze(a.view((1, 4, 1)), dim=2).shape)

tensor([[2., 0., 0., 1.]])
torch.Size([1, 4])


#### expand_dims 함수 대신에 unsqueeze 함수가 있다. (차원 축소)

In [29]:
print(torch.unsqueeze(a.view((1, 4)), dim=2))
print(torch.unsqueeze(a.view((1, 4)), dim=2).shape)

tensor([[[2.],
         [0.],
         [0.],
         [1.]]])
torch.Size([1, 4, 1])


#### 여러 함수가 torch.명령어 형태, tensor.명령어 로  사용 할 수 있다. 

In [32]:
a = torch.arange(10).view(5, 2)
a

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [33]:
a.transpose(1, 0)

tensor([[0, 2, 4, 6, 8],
        [1, 3, 5, 7, 9]])

In [34]:
torch.transpose(a, 1, 0)

tensor([[0, 2, 4, 6, 8],
        [1, 3, 5, 7, 9]])

# 5. 함수 끝에 `_`를 붙이면 inplace명령이 된다.
(안되는 함수가 존재함)

In [35]:
a

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [36]:
print(a)
print(a.transpose_(0, 1))
print(a)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])
tensor([[0, 2, 4, 6, 8],
        [1, 3, 5, 7, 9]])
tensor([[0, 2, 4, 6, 8],
        [1, 3, 5, 7, 9]])


In [37]:
a.shape

torch.Size([2, 5])

In [38]:
# view함수에는 inplace명령이 구현되어 있지 않다. 
print(a.view(-1, 1), a.view(-1, 1).shape)
print(a.view_())
print(a)

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

# 6. 형상 연산 중 유용한 것

In [47]:
a = torch.arange(10).view(5, 2)
a

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [40]:
b = torch.arange(10).view(2, 5)
b

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [48]:
print(a.view_as(b))
print(a.reshape_as(b))

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


# 7. indexing, slicing

In [49]:
a[0]

tensor([0, 1])

In [50]:
a[0, 1]

tensor(1)

In [51]:
a[4, 1]

tensor(9)

In [52]:
a[:2]

tensor([[0, 1],
        [2, 3]])

# 8. Tensor를 나누거나 합치기

#### 나누기_chunk

In [53]:
c = torch.rand(3, 6)
c

tensor([[0.0623, 0.5351, 0.2084, 0.7141, 0.2245, 0.5036],
        [0.2471, 0.3171, 0.7625, 0.8807, 0.9228, 0.6145],
        [0.4165, 0.6234, 0.0507, 0.3840, 0.6899, 0.2145]])

In [55]:
c1, c2, c3 = torch.chunk(c, 3, dim=0)  # 3개로 나눈다
print(c1)
print(c2)
print(c3)

tensor([[0.0623, 0.5351, 0.2084, 0.7141, 0.2245, 0.5036]])
tensor([[0.2471, 0.3171, 0.7625, 0.8807, 0.9228, 0.6145]])
tensor([[0.4165, 0.6234, 0.0507, 0.3840, 0.6899, 0.2145]])


In [56]:
c1, c2, c3 = torch.chunk(c, 3, dim=1)  # 3개로 나눈다
print(c1)
print(c2)
print(c3)

tensor([[0.0623, 0.5351],
        [0.2471, 0.3171],
        [0.4165, 0.6234]])
tensor([[0.2084, 0.7141],
        [0.7625, 0.8807],
        [0.0507, 0.3840]])
tensor([[0.2245, 0.5036],
        [0.9228, 0.6145],
        [0.6899, 0.2145]])


#### 나누기_split

In [60]:
torch.split(c, 1, dim=1) # 1개씩 나눔 = 6개로 쪼개짐

(tensor([[0.0623],
         [0.2471],
         [0.4165]]),
 tensor([[0.5351],
         [0.3171],
         [0.6234]]),
 tensor([[0.2084],
         [0.7625],
         [0.0507]]),
 tensor([[0.7141],
         [0.8807],
         [0.3840]]),
 tensor([[0.2245],
         [0.9228],
         [0.6899]]),
 tensor([[0.5036],
         [0.6145],
         [0.2145]]))

In [58]:
torch.split(c, 2, dim=1) # 2개씩 나눔 = 3개로 쪼개짐

(tensor([[0.0623, 0.5351],
         [0.2471, 0.3171],
         [0.4165, 0.6234]]),
 tensor([[0.2084, 0.7141],
         [0.7625, 0.8807],
         [0.0507, 0.3840]]),
 tensor([[0.2245, 0.5036],
         [0.9228, 0.6145],
         [0.6899, 0.2145]]))

In [59]:
torch.split(c, 3, dim=1) # 3개씩 나눔 = 2개로 쪼개짐

(tensor([[0.0623, 0.5351, 0.2084],
         [0.2471, 0.3171, 0.7625],
         [0.4165, 0.6234, 0.0507]]),
 tensor([[0.7141, 0.2245, 0.5036],
         [0.8807, 0.9228, 0.6145],
         [0.3840, 0.6899, 0.2145]]))

#### 결합하기_cat

In [61]:
a = torch.ones(2, 3)
b = torch.zeros(3, 3)
a, b

(tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]))

In [62]:
torch.cat([a, b], dim=0)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [63]:
torch.cat([a, b], dim=1)

RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 2 but got size 3 for tensor number 1 in the list.

#### 결합하기_stack

In [64]:
a = torch.ones_like(b)
a, a.size()

(tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]),
 torch.Size([3, 3]))

In [65]:
b, b.size()

(tensor([[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]),
 torch.Size([3, 3]))

In [68]:
torch.stack([a, b], dim=0), torch.stack([a, b], dim=0).size()

(tensor([[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],
 
         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]]),
 torch.Size([2, 3, 3]))

In [66]:
torch.stack([a, b], dim=1), torch.stack([a, b], dim=1).size()

(tensor([[[1., 1., 1.],
          [0., 0., 0.]],
 
         [[1., 1., 1.],
          [0., 0., 0.]],
 
         [[1., 1., 1.],
          [0., 0., 0.]]]),
 torch.Size([3, 2, 3]))

In [67]:
torch.stack([a, b], dim=2), torch.stack([a, b], dim=2).size()

(tensor([[[1., 0.],
          [1., 0.],
          [1., 0.]],
 
         [[1., 0.],
          [1., 0.],
          [1., 0.]],
 
         [[1., 0.],
          [1., 0.],
          [1., 0.]]]),
 torch.Size([3, 3, 2]))

#### 결합하기_tile

In [69]:
torch.tile(a, (3, 1))

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [70]:
torch.tile(a, (1, 2))

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [71]:
torch.vstack

<function torch._VariableFunctionsClass.vstack>

In [72]:
torch.hstack

<function torch._VariableFunctionsClass.hstack>